### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by themihai** [instacount/appengine-counter#27]
Transactions - You can't have transactions on shared counters. On transactions you would get data contention (Concurrency exception) which is exactly what you are trying to avoid using shards.

Atomic - Counter increment/decrement operations are not atomic because you don't have transactions and datastore doesn't support increment/decrement operations. memcache and datastore can/does run out of sync.

The implementation holds value but the claims from the readme file are not doable using the appengine platform. At most you can provide a high performance counter which is eventual consistent. For example a page visits counter. Uses cases that require decrements may end-up with odd situations when your items list is zero but the counter is positive (e.g. + 10).

**Comment by themihai** [comment]
It seems I was actually wrong. Sorry for the noise. The more shards you have the less chances to get concurrency exceptions. It's worth nothing that you are limited to one write per shard.

**Comment by sappenin** [comment]
Hi @themihai, thanks for posting.  Looks like you figured out the AppEngine transaction model more clearly. 

About the Datastore throughput, I've read in various Google documentation (and forums) over the years that the Datastore can support ~5 transactional writes per-second per entity.  I've also seen people say ~3 and ~1 write per-second, per entity.  

In my experience, this varies a lot based on the health of the Datastore at any given moment, but for planning/estimation purposes, I use 3 writes-per-second, per entity.  This means that you should see ~3 increments/decrements per second for each shard in your counter.

This is just approximate though -- a given series of increments may hit a particular shard more than another, but multiplying the number of shards by 3 should give you a close approximation of counter throughput -- but real-world results will vary.
