### ISSUE TITLE
newCounterCreated() in CounterOperation always false for newly created Counter 

### ISSUE THREAD

**Issue by ramesh-dev** [instacount/appengine-counter#34]
Hi, 

When calling increment method with non existing counter name, the response "CounterOperation" instance always returns false for newCounterCreated() even though it automatically creates a new counterData for it. I checked the code, and found out that the following line in **mutateCounterShard** method, the newlyCreated property is set with static boolean **false** as value. 

`		final Work<CounterOperation> atomicIncrementShardWork = new IncrementShardWork(counterData,
			incrementOperationId, optShardNumber, amount, false);`

instead it should take the value from counterDataGetCreateContainer response like below, 

```
boolean isNewlyCreated = counterDataGetCreateContainer.isNewCounterDataCreated();
final Work<CounterOperation> atomicIncrementShardWork = new IncrementShardWork(counterData,
			incrementOperationId, optShardNumber, amount, isNewlyCreated);
```

Please have a look. 
Thanks!

**Comment by sappenin** [comment]
Fixed by #35.
